name: Deploy Preview to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Install Functions dependencies
        working-directory: functions
        run: npm ci

      - name: Deploy preview to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SAGCC_04 }}
          projectId: sagcc-04
          channelId: pr-${{ github.event.pull_request.number }}
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
